# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fits a zero-inflated generalized Poisson by EM 
#' 
#' @param x The data.
#' @export
NULL

f12 <- function(x, m) {
    .Call(`_empiricalzip_f12`, x, m)
}

#' Fits a zero-inflated generalized Poisson by EM 
#' 
#' @param x The data.
#' @export
NULL

gpdMixture <- function(x, eta, lambda, theta) {
    .Call(`_empiricalzip_gpdMixture`, x, eta, lambda, theta)
}

rcpp_hello_world <- function() {
    .Call(`_empiricalzip_rcpp_hello_world`)
}

